### ISSUE TITLE
Make video file names more readable

### ISSUE THREAD

**Issue by danielfernau** [unifi-toolbox/unifi-protect-video-downloader#14]
The UI file name scheme is `Front Door - 2-9-2020, 11.21.12pm.mp4`.
- `Camera Name - M(M)-D(D)-YYYY, H(H).M(M).S(S)pp.mp4`
- `{camera_name} - {%-m}-{%-d}-{%Y}, {%-I}.{%-M}.{%-S}{%p}.mp4`

The date and time in the file name equals start date and time of the clip.

Maybe use a zero-padded decimal format. Some suggestions:
- (12-hour clock)
  - `{camera_name} - {%m}-{%d}-{%Y}, {%I}.{%M}.{%S}{%p}.mp4`
  - e.g. `Front Door - 02-09-2020, 11.21.12pm.mp4`
- (24-hour clock)
  - `{camera_name} - {%m}-{%d}-{%Y}, {%H}.{%M}.{%S}.mp4`
  - e.g. `Front Door - 02-09-2020, 23.21.12.mp4`
- (24-hour clock, no additional `.`s in the name)
  - `{camera_name} - {%m}-{%d}-{%Y}, {%H}h{%M}m{%S}s.mp4`
  - e.g. `Front Door - 02-09-2020, 23h21m12s.mp4`
- (24-hour clock, year-month-date, no additional `.`s in the name)
  - `{camera_name} - {%Y}-{%m}-{%d}, {%H}h{%M}m{%S}s.mp4`
  - e.g. `Front Door - 2020-09-02, 23h21m12s.mp4`

Additionally, it might make sense to append the time zone to the file name.

https://github.com/unifi-toolbox/unifi-protect-video-downloader/blob/2c41599e4485d7d18f9352d45d5d3d1415c80c6a/protect_archiver/client.py#L291

**Comment by danielfernau** [comment]
New file name scheme is likely to be:
`{camera_name} {camera_id_last_4} - {%Y}-{%m}-{%d} - {%H}.{%M}.{%S%z}`

---

- camera name
- 4 last characters of camera ID (to be able to distinguish between cameras with otherwise identical names)
- date in format yyyy-mm-dd
- time and time zone in format hh.mm.ss±zzzz

---

**Example:** 
```
Front Door (21a3) - 2020-03-10 - 00.00.00+0100.mp4
Front Door (21a3) - 2020-03-10 - 01.00.00+0100.mp4
Front Door (21a3) - 2020-03-10 - 02.00.00+0100.mp4
Front Door (21a3) - 2020-03-10 - 03.00.00+0100.mp4
Front Door (21a3) - 2020-03-10 - 04.00.00+0100.mp4
Front Door (21a3) - 2020-03-10 - 05.00.00+0100.mp4
```

**Comment by dcramer** [comment]
+1 on the filename. Keeps it human readable, unique (camera last 4) and helps make it easier to understand if you're working with other systems that are using TZs.

**Comment by danielfernau** [comment]
Thanks! Definitely looks a lot cleaner compared to the old format – let's merge it.
