### ISSUE TITLE
When start is invalid (no video) it errors

### ISSUE THREAD

**Issue by sirtastic** [unifi-toolbox/unifi-protect-video-downloader#21]
Is it possible to start downloading from the first available start time for a given date?

**Comment by danielfernau** [comment]
In version 1.x it's not directly supported – but version 2.x will use the given start date/time or the first available date/time of recordings available for each camera, whatever comes first. This functionality has been partially implemented as part of the new 'sync' command in v2.0.0: https://github.com/unifi-toolbox/unifi-protect-video-downloader/pull/18/
It will also be available as part of the `download` command.

As long as you're using v1.x, you can add the `--ignore-failed-downloads` option to skip non-existing segments.

**Comment by danielfernau** [comment]
v2.0.0 has been merged into the master branch: #37
