### ISSUE TITLE
Download failed with status 500 Internal Server Error

### ISSUE THREAD

**Issue by ChadOhman** [unifi-toolbox/unifi-protect-video-downloader#26]
Hello,

Amazing work with this - I can see the potential and this is potentially exactly what I'm looking for... however I'm running into the above error. Here's my run log:
```
chad@ubnt-mdnld:~/unifi-protect-video-downloader$ python3 main.py --address=10.0.0.2 --port=7443 --username="###########" --password="##########" --cameras="5db13a7802081a03e70003ef" --start="2020-04-05 00:00:00-0700" --end="2020-04-21 23:00:00-0700" --dest=./download --skip-existing-files --use-subfolders
Successfully authenticated as user chadohman
Successfully requested API Access Key
Successfully retrieved data from /api/bootstrap
Cameras found:
Front Yard (5db13a7802151a03e70003f0)
South Yard (5db13a7801db1a03e70003ed)
Car Park (5db13a7801f61a03e70003ee)
Back Yard (5db13a7802081a03e70003ef)
Downloading video files between 2020-04-05 00:00:00-07:00 and 2020-04-21 23:00:00-07:00 from 'https://10.0.0.2:7443/api/video/export'

Downloading footage for camera 'Back Yard' (5db13a7802081a03e70003ef)
Created path /home/chad/unifi-protect-video-downloader/download/2020/04/05/Back_Yard_03ef
Downloading video for time range 2020-04-05 00:00:00-07:00 - 2020-04-05 00:59:59-07:00 to /home/chad/unifi-protect-video-downloader/download/2020/04/05/Back_Yard_03ef/Back_Yard_03ef_2020-04-05--00-00-00-0700_2020-04-05--00-59-59-0700.mp4
Download failed with status 500 Internal Server Error

To skip failed downloads and continue with next file, add argument '--ignore-failed-downloads'
0 files downloaded, 0 files skipped, 0 files total
```

I'm running Ubuntu 18.04.04. What am I doing wrong? Thank you for any help you can provide.

**Comment by ChadOhman** [comment]
Problem solved - I was going too far back.

**Comment by danielfernau** [comment]
Hi there,

thank you for opening (and closing 😄) this issue, and sorry for my delayed response.

Yes, if you go too far back or have cameras that are configured to only record motion, you can expect to get these `status 500` errors. If you add the `--ignore-failed-downloads` flag to your command line, the software will skip these segments. This is especially useful when you don't really know at which date and time the first available recordings on the NVR's HDD start or, as mentioned earlier, you have motion-only recording enabled for some or all cameras.

Feel free to send me another message in case you need additional help getting things up and running or if you have questions or problems!

**Comment by ChadOhman** [comment]
Yeah I should have thought of that off the start. I used the `--ignore-failed-downloads` flag after my first run, it seems corrupted video files are a common thing for Unifi Protect.

Appreciate all of the work you put into this! :)
