### ISSUE TITLE
skip existing files flag does nothing 

### ISSUE THREAD

**Issue by aetaric** [unifi-toolbox/unifi-protect-video-downloader#32]
I'm running the latest 2.0.0 from HEAD. Multiple runs of `protect-archiver events` continually redownloads the files despite them already existing on disk.

I'd rather have this flag working as I'm downloading events to a system to stage them for transfer into S3 for long term off-site storage.

[output.txt](https://github.com/unifi-toolbox/unifi-protect-video-downloader/files/4743068/output.txt)

**Comment by danielfernau** [comment]
Hi @aetaric – thanks for the hint! 

The code in the `events` part of the software to handle the `--skip-existing-files` flag was missing entirely. It only worked for the `download` command. 

Resolved in commit 37d327ef38dd67daa787b053e494ca2550ae1712.

**Comment by aetaric** [comment]
pulled down latest master and rebuilt wheel using poetry, working perfectly now! thanks!

**Comment by danielfernau** [comment]
You're welcome, thanks for the feedback!
