### ISSUE TITLE
Apple M1 silicon support

### ISSUE THREAD

**Issue by tauren** [unifi-toolbox/unifi-protect-video-downloader#39]
I just received a new M1 MacBook Pro and am trying to get this project running. I installed Docker for Mac M1 Preview. And then I ran this:

```
❯ docker run --volume /path/on/host/machine:/downloads unifitoolbox/protect-archiver --help

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Usage: protect-archiver [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  download  Download footage from a local UniFi Protect system
  events    Download event recordings from UniFi Protect to a local...
  sync      Synchronize your UniFi Protect footage to a local destination
```  

It would be nice to natively support `linux/arm64/v8` and not show the warning.

**Comment by danielfernau** [comment]
Thanks for the suggestion! I'll look into building an ARM/M1 version in a bit and post updates here.

**Comment by tauren** [comment]
Perfect, looking forward to your progress! I'd love to get this working on my new Mac.

**Comment by danielfernau** [comment]
Hi @tauren 

In addition to `linux/amd64` images, there will also be `linux/arm64` images for every build from now on. 
The first `arm64` image is already available (link below) if you want to try it out. Let me know if it works; I'll have a look at #40 in case the issue persists with the new image architecture.

🔗 [Docker Hub (unifitoolbox/protect-archiver:latest)](https://hub.docker.com/layers/unifitoolbox/protect-archiver/latest/images/sha256-d18c2b990414445758338906e7914d9ef1023c81e0d06f4de24101c1aa5563da?context=repo)

**Comment by tauren** [comment]
@danielfernau Thank you. I did the following to upgrade, and it no longer crashes or shows architecture warnings. However, all it does is immediately create empty files and then exit.

```
docker pull unifitoolbox/protect-archiver:latest
```

```
docker run --volume /Users/tauren/Downloads/17th:/downloads unifitoolbox/protect-archiver download --address=192.168.0.2 --username="unifi-toolbox" --password="PASSWORD" --cameras="5f77b53003445a03e70003ee" --start="2021-02-23 09:00:00-0800" --end="2021-02-23 14:00:00-0800" --skip-existing-files --touch-files --use-subfolders --download-request-timeout 300 /downloads

Getting camera list
Successfully authenticated as user unifi-toolbox
Successfully retrieved data from /api/cameras
Cameras found:
- Int Garage (5f77b53003835a03e70003f0)
- Int Front Room (5f77b530039e5a03e70003f1)
- Int Kitchen Birdseye (5f77b53003445a03e70003ee)
- Ext Backyard (5f77b53003d65a03e70003f3)
- Ext Front Porch (5f77b531003e5a03e70003f6)
- Ext Garage Yard (5f77b53100265a03e70003f5)
- Ext Side Porch (5f77b53003635a03e70003ef)
- Int Basement (5f77b531000e5a03e70003f4)
- Ext Side Yard South (5f77b53100775a03e70003f8)
- Ext Driveway (5f77b53003205a03e70003ed)
- Int Dining Room (5f8696ee03b22503e7009f75)
Downloading footage for camera 'Int Kitchen Birdseye' (5f77b53003445a03e70003ee)
Downloading video files between 2021-02-23 09:00:00-08:00 and 2021-02-23 14:00:00-08:00 from 'https://10.10.10.2:7443/api/video/export' for camera Int Kitchen Birdseye

...
...
...

Downloading video for time range 2021-02-23 13:00:00-08:00 - 2021-02-23 13:59:59-08:00 to /downloads/2021/02/23/Int Kitchen Birdseye (03ee)/Int Kitchen Birdseye (03ee) - 2021-02-23 - 13.00.00-0800.mp4
0 files downloaded (0.0 b), 5 files skipped, 5 files total
File /downloads/2021/02/23/Int Kitchen Birdseye (03ee)/Int Kitchen Birdseye (03ee) - 2021-02-23 - 13.00.00-0800.mp4 already exists on disk and argument '--skip-existing-files' is present - skipping download
```

Any idea why it wouldn't be downloading content?

**Comment by tauren** [comment]
Small nudge... :) 

I'd sure like to get this working. Any thoughts?

**Comment by danielfernau** [comment]
Sorry for the late reply and thanks for your patience!
Sadly, I don't have enough free time at the moment to properly maintain my projects, fix stuff or reply to issues as fast as I would like to. My day job's workload almost doubled over the past ~1 year due to the whole pandemic situation. Really hope things return to normality soon...

I tried recreating the issue you're running into just now. At the moment I only have a UDM Pro actively running with cameras attached to it, and a few firmware updates ago the logic around authentication completely broke. So until I either get around to fixing that issue, or get my CloudKey Gen2+ up and running again in a test environment, I can't really test in-depth and can only guess. Maybe try running it without the `--touch-files` argument and see if that makes a difference? There's a chance that some of the past firmware updates included API changes that broke more than just the authentication part of the tool. Also, I noticed that for some reason your command contains `--address=192.168.0.2` but the log output reads `10.10.10.2`...

**Comment by danielfernau** [comment]
Hi @tauren 

Thank you for your patience, I've finally managed to update some parts the tool. It should now be more reliable and fully compatible to UniFi OS-based Protect systems.

The new release – [v2.0.1](https://github.com/unifi-toolbox/unifi-protect-video-downloader/releases/tag/v2.0.1) – is now available for download, for linux/amd64 as well as linux/arm64 platforms. Please have a look and let me know if the problem still occurs.
