### ISSUE TITLE
Videos are "sparse" which confuses media players

### ISSUE THREAD

**Issue by purpleidea** [unifi-toolbox/unifi-protect-video-downloader#4]
Hi,

Thanks for your script. I was playing with it in lieu of using rsync, because I'm really not in the mood to reverse the *.ubv files =D

I noticed it pulls down the videos in "chunks" of one hour. However inside each of those chunks there may be only a few minutes or a few separate instances of a few minutes (usually when "record motion only" is enabled).

Playing back those files seems to be a bit confusing for the media players, since they see the full timestamps, however during play they skip forward over the "dead" missing parts, if you try and rewind they never skip backwards because they hit the missing part. Maybe a chapter marker could be added at each event so reversing is possible?

Maybe I'm misunderstanding the situation, but HTH.

**Comment by danielfernau** [comment]
Hi James

Thanks for your feedback. I know what you mean and it's an issue with the export API itself, not the script. Some video players have problems with the playback of these incomplete stream exports.

However, the script's main purpose is to automate the API calls for requesting files from the CloudKey storage and my goal is to keep it as simple as possible for now. It's mainly designed to be the connector between the UniFi Protect system running on the CloudKey and any kind of additional backup/export/archive/etc. scripts processing the files after exporting them. 

The blank parts within the files are not generated by my script but rather by the UniFi Protect system itself during export from *.ubv to *.mp4 and I've not yet found a reliable way of removing (or marking) the blank parts from the downloaded files.

There might be an ffmpeg command or similar tool to process the files afterwards as part of a script and clean them up – but I have not yet found anything useful. 

A possible solution for your situation with event-based recordings would be to only request the event video files directly within the given time range. That seems to be possible, too. Have a look at issue #3 – he has already figured out how to talk to the events API endpoint and I'm going to implement his work soon, adding this feature to the main script.

I'll keep this issue open for now and add updates as necessary.
If anyone reading this knows more about automatically removing blank parts from video files or has any kind of helpful idea: please post it as a comment here.

**Comment by danielfernau** [comment]
Please use the `protect-archiver events` command for downloading video files from cameras that are configured to record only motion events. 

This command is available in the v2.0.0 branch: https://github.com/unifi-toolbox/unifi-protect-video-downloader/tree/v2.0.0

Usage is documented here (and in the software itself): https://github.com/unifi-toolbox/unifi-protect-video-downloader/pull/20
