### ISSUE TITLE
add "rsync style" resuming

### ISSUE THREAD

**Issue by purpleidea** [unifi-toolbox/unifi-protect-video-downloader#5]
Running a command like:

```
python3 ~/code/src/unifi-protect-video-downloader/main.py --address=192.168.100.110 --username="download" --password="hunter2" --cameras="all" --start="2019-01-01 00:00:00-0500" --end="2021-01-05 00:00:00-0500" --dest=./videos --skip-existing-files --use-subfolders --ignore-failed-downloads
```

Works great, however it always re-checks the whole time interval. It would be great to automatically flag ranges that have already been checked, and to never download (too far, in case of timesync issues) into the future.

If someone has already baked in such a solution, please lmk.

Thanks!

**Comment by danielfernau** [comment]
Good idea(s), thanks. 

Checking the already downloaded files could be further improved by looking at the file names and/or existing folder structure in the specified download destination directory at the very beginning of the script and then reducing the given time range accordingly. 

Currently however, the script already does something similar on a file-by-file basis without actually contacting the CloudKey for each already downloaded file. Everything happens locally until the next file that needs to be downloaded is found. 

Regarding the "too far into the future" issue: this can be solved by adding simple input validation to the `--end` command line argument. I'll probably add that soon.

**Comment by purpleidea** [comment]
> Checking the already downloaded files could be further improved by looking at the file names and/or existing folder structure in the specified download destination directory at the very beginning of the script and then reducing the given time range accordingly.

We could also be yucky and leave a token. Eg `.lastwhatever` or something and store the date in there.

> Currently however, the script already does something similar on a file-by-file basis without actually contacting the CloudKey for each already downloaded file. Everything happens locally until the next file that needs to be downloaded is found.

Hmmm, can you elaborate? This would mean we'd have to keep the 10000's of empty video files though, right?

**Comment by danielfernau** [comment]
> We could also be yucky and leave a token. Eg `.lastwhatever` or something and store the date in there.

Good idea, that's probably the easiest way to solve this. At the end of every processed one-hour chunk write the `end` timestamp of that chunk to a file. Keep that file up-to-date as the script goes through the given time range. If the script runs again, check if the timestamp in the file is between given start and end time, and adjust the start time accordingly. I'll try to implement it that way.

> Hmmm, can you elaborate? This would mean we'd have to keep the 10000's of empty video files though, right?

Yes, that would require keeping all files, even the empty ones. The script "builds" the file name, checks if that file already exists locally and skips the download process if it does. I have to admit – it works but is definitely not the most elegant solution 😄

**Comment by dcramer** [comment]
I'm here with a similar goal in mind (archiving all video footage). So far my hack has been to just run it hourly on a cron, but I haven't dug deep enough into the API to know if that's going to create issues. Is it possible that Unifi is making near-time video available before the end of the hour, and thus we'd end up with partial video files that would later have been completed?

Here's my cron if its helpful:

```
- name: install archiver cronjob
  cron:
    name: "archive camera footage"
    minute: "0"
    job: >
      docker
      -v "{{ nas_mount_folder }}/cameras:/output"
      run zeeg99/protect-archiver 
      --address=unifi
      --username={{ protect_username }} 
      --password="{{ protect_password }}" 
      --cameras=all 
      --start="$(date -d '-2 days')"
      --end="$(date -d '-1 day')"
      --dest=/output/ 
      --skip-existing-files 
      --use-subfolders
      --ignore-failed-downloads
```

Aside i think start/end are mixed up in the docs and/or they are interchangeable. Also happy to contribute my Dockerfile for this (its in my fork at the moment), as I'm using it to keep things isolated on the system.

**Comment by danielfernau** [comment]
@dcramer Automating it with a cron should work fine. At least in my setup this has not caused any issues so far. I'm also not entirely sure how the API and the file processing works in detail but I think the recordings are written directly to disk. So it's unlikely that some kind of post-processing of the files causes partial video files. I'd guess that the reason why they're using these special ubv containers is to allow for some kind of "append the stream(s) to the end of the ubv file until the file is x Gigabytes large, then start the next file". And the files can only be read and exported to mp4 in combination with the entries from the database where the Protect system stores which ubv file contains which recordings.

What exactly do you mean with "start/end are mixed up in the docs"? Did you try to use a start date that is later than the end date? And what happened?

**Comment by dcramer** [comment]
@danielfernau i think i used older end date, newer start date, and it downloaded *something*, though far less than reversing them. I also looked at the comments in that function afterwards and it seemed like it expected start to be newer. tbqh caffeine withdraw happening right now and my memory is not coherent ;)

**Comment by danielfernau** [comment]
@dcramer Just tried downloading something with start at midnight and end at 4am – which worked as expected, and then tried it with start at 4am and end at midnight, which downloaded nothing. It basically just produced some console output which looks similar to the output generated during regular downloads but much shorter. But at the end it says `0 files downloaded, 0 files skipped, 0 files total`. I'll add a warning for "end time before start time" and add an non-zero exit code for that, though. And yes, running low on caffeine can get dangerous after a while ;)

**Comment by dcramer** [comment]
Toying with this here:

https://github.com/dcramer/unifi-protect-video-downloader

API is quite different right now and is a normal python package, but you can do this:

```
unifi-protect-sync --username={username}--password={password} --dest /tmp/cameras
```

I'm not sure if its foolproof yet, but it goes back to the start of the history that Unifi says exists (from bootstrap), and keeps a statefile to mark the last downloaded video. I'm also attempting to get it to only be full periods of time so you don't end up with partial videos.

In my branch the old main.py is available at unifi-protect-download.
