### ISSUE TITLE
Invalid value for '--end' invalid datetime error message doesn't make any sense

### ISSUE THREAD

**Issue by nyanchor** [unifi-toolbox/unifi-protect-video-downloader#71]
# Issue

I'm seeing strange error messages when trying to download using docker and here are by basic configs

```bash
...
START=$(date -d "yesterday" +"%Y-%m-%d 00:00:00")
STOP=$(date +"%Y-%m-%d 00:00:00:00")
```

running with docker
```bash
docker run --volume $HOME:/videos \
  unifitoolbox/protect-archiver download \
  --address ${ADDRESS_OF_PROTECT} \
  --username ${USERNAME} --password ${PASSWORD} \
  --start "${START}" --end "${STOP}" ${SOURCE}
```
generates this error:
```bash
...
--start '2022-01-27 00:00:00' --end '2022-01-28 00:00:00:00' /var/tmp/videos
Usage: protect-archiver download [OPTIONS] DEST

Error: Invalid value for '--end': invalid datetime format: 2022-01-28 00:00:00:00. (choose from %Y-%m-%d, %Y-%m-%dT%H:%M:%S, %Y-%m-%d %H:%M:%S, %Y-%m-%d %H:%M:%S%z)
```
the start and end times clearly follow the specified format. I've switched multiple formats of the `...%S:%z) to no avail; may be I'm missing something?

**Comment by danielfernau** [comment]
Hi @nyanchor

Try adjusting your `STOP=$(date +"%Y-%m-%d 00:00:00:00")` line to either
- `STOP=$(date +"%Y-%m-%d 00:00:00-0500")` (UTC-5, EST) or `STOP=$(date +"%Y-%m-%d 00:00:00+0100")` (UTC+1, CET) if you want to use the `%z` (time zone) parameter (note: there's no `:` between `%S` and `%z` in `%H:%M:%S%z`)

or

- `STOP=$(date +"%Y-%m-%d 00:00:00")`, leaving out the `%z` parameter. The software will then default to the time zone configured for your Docker host system.

Date/Time string formatting can be a bit annoying and confusing sometimes, so I hope my explanation makes sense :)
Have a great weekend!

**Comment by nyanchor** [comment]
Thanks, will update accordingly.

**Comment by nyanchor** [comment]
@danielfernau when looking at the download command, I don't see a way to specify a port number; everything seems to default to `443`, but I forwarded my connection to another IP and that requires I provide a specific port number. How can I do that?

**Comment by danielfernau** [comment]
@nyanchor currently, the port is hard-coded in https://github.com/unifi-toolbox/unifi-protect-video-downloader/blob/cadb100c97f50f51b8f1a1a155d10f22e602e09d/protect_archiver/client/__init__.py#L65 

In case you need to change it to something else, you'd have to do that manually in the code for now.

I'll add a feature request later to allow using a custom port specified via a command line parameter.

**Comment by nyanchor** [comment]
Since I'm working with the docker container image, that means I'll have to create my own docker container image with this specification.

**Comment by danielfernau** [comment]
Yes, that's correct. Feel free to reach out if you need any assistance with that.

**Comment by nyanchor** [comment]
@danielfernau just created a PR to address this issue, take a look when you can. Let me know if there are any changes I need to make to get this merged. Also, I noticed there's no CI/CD implemented for this repo to automatically test changes. I may come up with something using GitHub actions, but that'll be later.

**Comment by danielfernau** [comment]
@nyanchor Thanks a lot, looks good so far. I'll have another look at it as soon as I can and will keep you updated on the progress. 

Regarding CI/CD, yes, feel free to open issues and/or PRs with ideas whenever you find time to do so. 
I'm trying to keep this project alive in my spare time which has turned out to be quite a challenge, so any help is very welcome! The only automations currently in place are for the package and Docker image builds.

**Comment by nyanchor** [comment]
@danielfernau I'll added my own customizations to the project, once I'm done with those; I'll create another PRs. Also did some security scans of the docker images, there' are over 23 vulnerabilities. I'll try to address as much of them as I can before creating the PRs.

**Comment by danielfernau** [comment]
@nyanchor Thanks, sounds good. 👍 
As for the security updates, I'll look into this as well -- and probably set up something like Dependabot for this project while I'm at it so that dependencies can be updated easier and a bit more automated.
